### ISSUE TITLE
[Neoforge] [1.20.1] Game crashes when attacking a mob, and mobs are not aggresive.

### ISSUE THREAD

**Issue by KateReller** [danbrown/deltabox-issues#1] opened 2024-10-16 02:55 UTC
Crash log:
https://mclo.gs/qea2Rye

**Comment by danbrown** [comment] 2024-10-16 13:50
Hello! Thanks for the issue.

It seems to be a large modpack, what made you believe the error is caused by deltaboxlib?

Your error seems to be related to a mixin in the LivingEntity or AttributeMap class.
Doesn't make much sense that deltaboxlib is causing this error since it doesn't interact with entities or mobs at all...

I'll would check this mods first, since they add mixins to the class that is throwing the crash:
 ```the_bumblezone
modernfix
beansbackpacks
citadel
fabric_lifecycle_events_v1
goodending
lost_aether_content
elytratrims
radium
insanelib
curios
supplementaries
betterdeserttemples
caelus
copycats
createbigcannons
domesticationinnovation
valkyrienskies
blahaj
relics
unionlib
friendsandfoes
shieldsplus
botania
fabric_entity_events_v1
ars_nouveau
pointblank
bettercombat
witherstormmod
create
```

I'll close this issue since it is not related to deltaboxlib, I can reopen if for some reason it is the case

**Closed as completed by danbrown** 2024-10-16 13:50 UTC

**Comment by KateReller** [comment] 2024-10-16 22:13
My mistake. In my haste to diagnose a modpack, the wrong mod got identified as the culprit. Another library called [UnionLib](https://modrinth.com/mod/unionlib) was creating the errors. Sorry about this!

**Comment by danbrown** [comment] 2024-10-17 00:30
It is fine! Thanks for the report anyway!
